name: Checks

on:
  push:
    branches:
      - main

env:
  GO111MODULE: "on"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19.5

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

      - name: Unit tests
        run: make test
