name: Linter and tests

on:
  push:
    branches:
      - master

env:
  GO111MODULE: "on"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19.5

      - name: Check out code
        uses: actions/checkout@v3

      - name: make build
        run: make build

      - name: make lint
        run: make lint

      - name: make test
        run: make test
